services:
  
  xserver:
    image: devrt/xserver
    # ipc: host
    # security_opt:
    #   - seccomp:unconfined
    environment:
      - DISPLAY=:9
    ports:
      - "3000:80"
    # volumes:
    #   - .:/workspaces

  ros-master:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # image: fagnerpimentel/aprendendo_ros2:latest
    container_name: ros-env
    ipc: host
    volumes:
      - ../:/home/robot/ws_aprendendo_ros2/:rw
    depends_on:
      - xserver
    volumes_from:
      - xserver
    environment:  
      - ROS_MASTER_URI=:http://ros-master:11311    
      - DISPLAY=:9
      - LDS_MODEL=LDS-02
      - TURTLEBOT3_MODEL=burger
      - DONT_PROMPT_WSL_INSTALL=No_Prompt_please
    ports:
      - "3001:80"